import{S as b,a as w,i as h}from"./assets/vendor-24f26945.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const S="43048239-bd17c0d5033bfd52479da7a86",v="https://pixabay.com/api/";function f(o,e){const s={q:o,page:e,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0,key:S},n=new URLSearchParams(s);return fetch(`${v}?${n}`).then(t=>{if(!t.ok)throw new Error("Error!");return t.json()})}function m(o){return o.map(e=>`<li class="gallery__item">
        <a class="gallery-link" href="${e.largeImageURL}">
        <img src="${e.webformatURL}" data-source="${e.largeImageURL}" alt="${e.tags}">
       
        </a>
        <ul class="list-container">
          <li class="item-description"><h3>Likes</h3> <p>${e.likes}</p></li>
          <li class="item-description"><h3>Views</h3> <p>${e.views}</p></li>
          <li class="item-description"><h3>Comments</h3> <p>${e.comments}</p></li>
          <li class="item-description"><h3>Downloads</h3> <p>${e.downloads}</p></li>
        </ul>
       </li>`).join("")}const q=document.querySelector(".js-search-form"),c=document.querySelector(".js-gallery"),d=document.querySelector(".js-backdrop"),u=new b(".gallery a",{captionsData:"alt",captionDelay:250}),a=document.querySelector(".js-load-more");q.addEventListener("submit",$);a.addEventListener("click",E);const P={lines:13,length:38,width:17,radius:45,scale:1,corners:1,speed:.8,rotate:0,animation:"spinner-line-fade-quick",direction:1,color:"#ffffff",fadeColor:"transparent",top:"50%",left:"50%",shadow:"0 0 1px transparent",zIndex:2e9,className:"spinner",position:"absolute"},g=new w(P);let i=1,p="";function $(o){o.preventDefault(),y(),c.innerHTML="",i=1,p=o.target["user-search-query"].value.trim(),f(p,i).then(e=>{if(e.hits.length===0)return a.classList.add("is-hidden"),h.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});u.refresh(),c.innerHTML=m(e.hits),u.refresh(),e.total>15&&a.classList.remove("is-hidden")}).catch(e=>{console.log(e)}).finally(()=>{L()})}function y(){g.spin(d),d.classList.remove("is-hidden")}function L(){g.stop(),d.classList.add("is-hidden")}function E(){y(),i+=1,f(p,i).then(o=>{console.log(o.total);const e=Math.ceil(o.total/15);c.insertAdjacentHTML("beforeend",m(o.hits)),u.refresh();const{height:s}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"}),e===i&&(a.classList.add("is-hidden"),h.info({message:"We're sorry, but you've reached the end of search results.",position:"topLeft"}))}).catch(o=>{console.log(o)}).finally(()=>{L()})}
//# sourceMappingURL=commonHelpers.js.map
