import{a as b,S as w,b as S,i as f}from"./assets/vendor-31f1d635.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&u(a)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function u(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const v="43048239-bd17c0d5033bfd52479da7a86",q="https://pixabay.com/api/";async function h(r,e){try{return(await b.get(q,{params:{q:r,page:e,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0,key:v}})).data}catch{throw Error("Error!")}}function m(r){return r.map(e=>`<li class="gallery__item">
        <a class="gallery-link" href="${e.largeImageURL}">
        <img src="${e.webformatURL}" data-source="${e.largeImageURL}" alt="${e.tags}">
       
        </a>
        <ul class="list-container">
          <li class="item-description"><h3>Likes</h3> <p>${e.likes}</p></li>
          <li class="item-description"><h3>Views</h3> <p>${e.views}</p></li>
          <li class="item-description"><h3>Comments</h3> <p>${e.comments}</p></li>
          <li class="item-description"><h3>Downloads</h3> <p>${e.downloads}</p></li>
        </ul>
       </li>`).join("")}const P=document.querySelector(".js-search-form"),c=document.querySelector(".js-gallery"),l=document.querySelector(".js-backdrop"),d=new w(".gallery a",{captionsData:"alt",captionDelay:250}),n=document.querySelector(".js-load-more");P.addEventListener("submit",$);n.addEventListener("click",M);const E={lines:13,length:38,width:17,radius:45,scale:1,corners:1,speed:.8,rotate:0,animation:"spinner-line-fade-quick",direction:1,color:"#ffffff",fadeColor:"transparent",top:"50%",left:"50%",shadow:"0 0 1px transparent",zIndex:2e9,className:"spinner",position:"absolute"},g=new S(E);let i=1,p="";async function $(r){r.preventDefault(),y(),c.innerHTML="",i=1,p=r.target["user-search-query"].value.trim();try{const e=await h(p,i);if(e.hits.length===0)return n.classList.add("is-hidden"),f.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});d.refresh(),c.innerHTML=m(e.hits),d.refresh(),e.total>15&&n.classList.remove("is-hidden")}catch(e){console.log(e)}finally{L()}}function y(){g.spin(l),l.classList.remove("is-hidden")}function L(){g.stop(),l.classList.add("is-hidden")}async function M(){y(),i+=1;try{const r=await h(p,i);console.log(r.total);const e=Math.ceil(r.total/15);c.insertAdjacentHTML("beforeend",m(r.hits)),d.refresh();const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),e<=i&&(n.classList.add("is-hidden"),f.info({message:"We're sorry, but you've reached the end of search results.",position:"topLeft"}))}catch(r){console.log(r)}finally{L()}}
//# sourceMappingURL=commonHelpers.js.map
